### ISSUE TITLE
Code no longer compiles

### ISSUE THREAD

**Issue by coder543** [Marwes/haskell-compiler#2]
This got referenced [over here](https://www.reddit.com/r/haskell/comments/761zb7/a_haskell_compiler_written_in_rust/), and it is an interesting project. Unfortunately, the code seems to pre-date stable Rust v1.0, which means a lot of it is broken.

You probably have other priorities, I just figured I would make a note here that the code has bitrotted, until such time as anyone steps up to fix it.

**Comment by Marwes** [comment]
That should teach me to assume things :) ([last paragraph](https://www.reddit.com/r/haskell/comments/761zb7/a_haskell_compiler_written_in_rust/dob6gu5/)).

Fixed with 9a15b0188cb71c149877e15fa0718489c2cbeb8f (small regression due to a fix in rustc after 1.0)

**Comment by coder543** [comment]
sadly, this doesn't fix it.

![errors](https://user-images.githubusercontent.com/726063/31551476-a911cc32-b002-11e7-9d79-8ac0f859e8da.png)

compiling with `rustc 1.22.0-nightly (a47c9f870 2017-10-11)`

using `cargo run --release`

**Comment by Marwes** [comment]
Woops. Only ran `cargo test`, that error only occurs with `cargo build`. That error may actually have been there since before 1.0.

**Comment by Marwes** [comment]
Now it builds as well 997a8b64ea57d27a547caba964081b680b1c5152.

Tested evaluating some programs and it appears that just writing `1` into the repl crashes it which I believe is because I never implemented type defaulting (ie transform `Num a => a` into `Int`). As long as the type is concrete it appears to work though.

**Comment by coder543** [comment]
Yep, it works now!
